# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rabin's Quill
email: rabingaire20@gmail.com
description: Hello Welcome I am Rabin Gaire from Nepal, Land of Mountains and a birthplace of lord buddha. I love programming. I am a rails developer. I also love JavaScript. I am familiar with react.js . Taking about a hobby I love to write about stuff (That's why this blog exists).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rabingaire.me" # the base hostname & protocol for your site
author: Rabin Gaire
favicon: "./favicon.ico"

twitter:
  username: rabin_gaire

gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - font-awesome-rails

# Build settings
markdown: kramdown
